module rosidl_parser {
  module srv {
    module MyService_Request_Constants {
      const short SHORT_CONSTANT = -23;
    };
    struct MyService_Request {
      short short_value;
      string string_value;
    };
    module MyService_Response_Constants {
      const unsigned long UNSIGNED_LONG_CONSTANT = 42;
    };
    struct MyService_Response {
      boolean boolean_value;
    };
  };
};
