module rosidl_parser {
  module action {
    module MyAction_Goal_Constants {
      const short SHORT_CONSTANT = -23;
    };
    struct MyAction_Goal {
      int32 input_value;
    };
    module MyAction_Result_Constants {
      const unsigned long UNSIGNED_LONG_CONSTANT = 42;
    };
    struct MyAction_Result {
      uint32 output_value;
    };
    module MyAction_Feedback_Constants {
      const float FLOAT_CONSTANT = 1.25;
    };
    struct MyAction_Feedback {
      float progress_value;
    };
  };
};
