# tmp_msgs/MyMessage
int16 SHORT_CONSTANT=-23
uint32 UNSIGNED_LONG_CONSTANT=42
float32 FLOAT_CONSTANT=1.25
bool BOOLEAN_CONSTANT=True
string STRING_CONSTANT='string_value'
wstring WSTRING_CONSTANT='wstring_value_\u2122'
string EMPTY_STRING_CONSTANT=''
int16 short_value
int16 short_value2
uint16 unsigned_short_value 123
int32 long_value
uint32 unsigned_long_value
int64 long_long_value
uint64 unsigned_long_long_value
float32 float_value
float64 double_value
float64 long_double_value
char char_value
wstring<=1 wchar_value
bool boolean_value
byte octet_value
int8 int8_value
uint8 uint8_value
int16 int16_value
uint16 uint16_value
int32 int32_value
uint32 uint32_value
int64 int64_value
uint64 uint64_value
string string_value
string<=5 bounded_string_value
wstring wstring_value
wstring<=23 bounded_wstring_value
wstring<=42 constant_bounded_wstring_value
int16[] unbounded_short_values
int16[<=5] bounded_short_values
string[] unbounded_values_of_bounded_strings
string[<=4] bounded_values_of_bounded_strings
int16[23] array_short_values
float32 int_and_frac_with_positive_scientific 19000000000.0
float32 int_and_frac_with_explicit_positive_scientific 19000000000.0
float32 int_and_frac_with_negative_scientific 1.1e-10
float32 int_and_frac 9e-05
float32 int_with_empty_frac 1.0
float32 frac_only 0.1
float32 int_with_positive_scientific 900000.0
float32 int_with_explicit_positive_scientific 900000.0
float32 int_with_negative_scientific 9e-05
float32 fixed_int_and_frac 8.7
float32 fixed_int_with_dot_only 4.0
float32 fixed_frac_only 0.3
float32 fixed_int_only 7.0