name: ROS 2 CI

on:
  pull_request:
    branches:
      - 'master'
      - 'ros2'
      - 'ros2/*'
      - 'dashing'
      - 'eloquent'
      - 'foxy'

jobs:
  test_environment: # Docker is not supported on OS X, and Windows.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        package: [rosidl_adapter, rosidl_cmake, rosidl_generator_c, rosidl_generator_cpp, rosidl_parser, rosidl_runtime_c, rosidl_runtime_cpp, rosidl_typesupport_interface, rosidl_typesupport_interface_c, rosidl_typesupport_cpp]
        os: [macOS-latest, windows-latest]
        ros_distribution: # Only include ROS 2 distributions for OS X, Windows
          - dashing
          - eloquent
          - foxy
    steps:
      - uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.0.17
        with:
          package-name: ${{ matrix.package }}

  test_environment_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - dashing
          - eloquent
          - foxy
        include:
          # Dashing Diademata (May 2019 - May 2021)
          - docker_image: ubuntu:bionic
            ros_distribution: dashing
            ros_version: 2
          # Eloquent Elusor (November 2019 - November 2020)
          - docker_image: ubuntu:bionic
            ros_distribution: eloquent
            ros_version: 2
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ubuntu:focal
            ros_distribution: foxy
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.0.17
        with:
          package-name: ${{ matrix.package }} 
          source-ros-binary-installation: ${{ matrix.ros_distribution }}
                                                                                
